version: '3.9'

services:
  auth-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: uZdJ8y92!lwL
      POSTGRES_DB: auth
    ports:
      - '5432:5432'
